server:
  port: 3000
  host: 0.0.0.0
  log_level: debug
  timeout:
    read: 5s
    write: 5s
    idle: 60s

database:
  host: localhost
  port: 5432
  database_name: lms
  user: root
  password: password
  sslmode: disable
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 5m
  timeout: 5s
